лучше так сделаю

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,6 +14,16 @@ jobs:
     runs-on: windows-latest
 
     steps:
+      - name: check token
+        run: |
+          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
+            echo "GITHUB_TOKEN is missing! Aborting workflow."
+            exit 1
+          else
+            echo "GITHUB_TOKEN is set. Continuing..."
+          fi
+        shell: bash
+        
       - name: Checkout repo
         uses: actions/checkout@v3
 
